modLoader="kotlindiscord"
loaderVersion="[3,)"
license="LGPL-3.0"

[[mods]]
modId="appliedflooring"
version="${version}"
displayName="Applied Flooring"
authors="Summpot"
description="High-performance ME flooring blocks and embedded multipart attachments for Applied Energistics 2"

[[dependencies.appliedflooring]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.appliedflooring]]
    modId="architectury"
    mandatory=true
    versionRange="[6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.appliedflooring]]
    modId="ae2"
    mandatory=true
    versionRange="[12,)"
    ordering="NONE"
    side="BOTH"
