# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.0.0
maven_group = io.github.summpot.appliedflooring
archives_name = appliedflooring
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.20.1

# Dependencies
architectury_api_version = 9.2.14

forge_version = 1.20.1-47.4.10
fabric_loader_version = 0.18.0
fabric_api_version = 0.92.6+1.20.1
fabric_kotlin_version = 1.13.7+kotlin.2.2.21

# Enable Athena connected textures in development runtime
runtime_athena = true
athena_fabric_1_20_1_version = mXJWSwbJ
athena_forge_1_20_1_version = DULOQFj7
athena_neoforge_1_21_1_version = dJgL278E

# Enable Fusion connected textures in development runtime
runtime_fusion = true
fusion_fabric_1_20_1_version = l3ukkiGe
fusion_forge_1_20_1_version = s8QN1MsD
fusion_neoforge_1_21_1_version = LohuCdof
fusion_fabric_1_19_2_version = lWRcz2dS
fusion_forge_1_19_2_version = ZUmMBgKs
